### PR TITLE
some files & some typos

### PR DESCRIPTION
**Pull request by trinajstica**
added missing files for linux and fixed some typos
now compiling .livecode and .oxtstack files on linux and windows from IDE is working "out of the box"

### CODE REVIEW

**Comment by PaulMcClernan** [comment]
I really need to be more careful about using OXT and NOT OTX!
Thank you! I did finally install a Linux build but I haven't had a chance to merge the linux specific files into this repo, so thanks for that as well! There's several things on Linux I'd like to fix if possible. I'm looking into modifiying the .desktop so that if you double click a stack files in your desktop environment it doesn't launch new or multiple instances of the IDE binary and need to link .desktop to the OXT Icon too. Will probably need to make a new installer package (.deb) for release when it gets to that point.

**Comment by trinajstica** [comment]
My openxtalk.desktop file looks like this:

[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Application
Name=OpenXTalk
Icon=/home/barko/bin/OpenXtalk-IDE-DontPanicEdition/OXTArtwork/OpenXTalkStackIcon.png
Exec=env GTK_DATA_PREFIX="" flock -xn .openxtalk.lck "/home/barko/bin/OpenXtalk-IDE-DontPanicEdition/IDE Bundle/Contents/Tools/OpenXTalk.x86_64" %U

And it works ok (just one instance of openxtalk ide).
This === env GTK_DATA_PREFIX="" === i'm using because I use dark mode desktop and I do not like oxt IDE in dark mode, so I force IDE to run with light mode.

**Comment by PaulMcClernan** [comment]
Thanks, I saved that for the OpenXTalk.desktop
I'd rather have DarkMode/Light mode be a toggle preference in the preferences UI.

I'm thinking it would be good to distribute OXT as an Linux OXT.AppImage portable package.

**Comment by trinajstica** [comment]
> Thanks, I saved that for the OpenXTalk.desktop I'd rather have DarkMode/Light mode be a toggle preference in the preferences UI.

I really like idea about Dark/Light mode from preferences to be choosed, but for me atm on linux is not working this part. I commented out from home.livecodescript file setAllToLightMode and setAllToDarkMode. It freezes openxtalk at start. So i need to kill the process from memory, comment out both of the procedures and after it starts ok. I didnt have time yet to check why is that.

**Comment by trinajstica** [comment]
I'm trying to find out where are setAllToDarkMode and setAllToLightMode functions? Any tips where can find them? In whole repo I can't seek them out.

**Comment by PaulMcClernan** [comment]
That's because setAllToDarkMode and setAllToLightMode are actually in a Builder Extension (macOS Native Tools) in one of the repos on my GitHub account. But I should merge that repo in with OXT soon, since I'm now using calls to it from the IDE Home stack's script! setAllToDarkMode and setAllToLightMode only apply to Apple platforms. I wrapped them in try/end try structure so it shouldn't throw any error if the extension isn't loaded.

BTW, I'm installing Xubuntu for working on Linux OXT testing against their two default dark themes.

**Pull request merged**
